### ISSUE TITLE
agregar tutorial de uso a notas y tareas

### ISSUE THREAD

**Issue by ariel-alvear** [srdavo/stepbro-website#10]
Para el diario aparece un pop-up acerca de cómo usar el diaro y sus funciones la primera vez que se le da click.

Sería bueno agregar este comportamiento a las notas y tareas

![Captura de pantalla 2024-11-16 a la(s) 8 39 39 p  m](https://github.com/user-attachments/assets/c6dba270-b3bc-4c01-868f-6a3b94e4d3af)

**Comment by srdavo** [comment]
Se agrego un botón de información en la sección de Notas y Tareas que abre una ventana con la información al igual que el Diario.
