### ISSUE TITLE
qué hace la nube con check en las notas?

### ISSUE THREAD

**Issue by ariel-alvear** [srdavo/stepbro-website#12]
un usuario que nunca ha visto la aplicación no sabe para qué sirve la nube con un check en las notas
![Captura de pantalla 2024-11-16 a la(s) 8 42 46 p  m](https://github.com/user-attachments/assets/ac7d30b9-049f-4192-82fa-b79dc327e30a)

**Comment by srdavo** [comment]
Se agregó la etiqueta "title" como tooltip indicando la acción del ícono
