### ISSUE TITLE
por qué hay más de una columna en notas?

### ISSUE THREAD

**Issue by ariel-alvear** [srdavo/stepbro-website#13]
¿Para qué se necesita más de una columna en notas? ¿Qué valor se agrega al usuario?

![Captura de pantalla 2024-11-16 a la(s) 8 44 09 p  m](https://github.com/user-attachments/assets/45b9a4b5-d5bc-4ff9-a054-c05fdbeed3bc)

**Comment by srdavo** [comment]
Comportamiento no deseado, no posible de replicar, estaremos al pendiente de más issues con este error.
