### ISSUE TITLE
Solo desplegar opciones correspondientes al seleccionar nota o carpeta

### ISSUE THREAD

**Issue by ariel-alvear** [srdavo/stepbro-website#15]
Si yo selecciono una nota y luego veo las opciones, me aparece que puedo borrar carpeta y otras opciones, si borro carpeta me aparece la validación de si estoy seguro, pero en realidad no estoy borrando una carpeta ni nada.
Deberían solo aparecer opciones que sean de acuerdo al elemento seleccionado:
- si selecciono una nota, que aparezca borrar nota y no borrar carpeta también
- si selecciono una carpeta, que aparezca borrar carpeta y no borrar nota también
- etc

![Captura de pantalla 2024-11-16 a la(s) 8 49 23 p  m](https://github.com/user-attachments/assets/a5535995-cec3-4cc9-a8fc-0defcc550ff4)

**Comment by srdavo** [comment]
Comportamiento no deseado, no se pudo reproducir.
