### ISSUE TITLE
Página principal no agrega valor por ahora

### ISSUE THREAD

**Issue by ariel-alvear** [srdavo/stepbro-website#9]
Sería bueno dejar de cara al usuario solo elementos que le den valor a la experiencia del usuario, por ejemplo uno entra directo a [https://stepbro.site/apps/notes/index?redirected](https://stepbro.site/apps/notes/index?redirected) y si una baja con el scroll llega a la parte donde dice página princial, y en la página principal solo uno puede ir directo a la app de notas. 

Sería bueno dejar oculto ese link a la página principal, hasta que la página principal tenga mayor valor y elementos que aportar, más que solo ir a la página de notas

![Captura de pantalla 2024-11-16 a la(s) 8 35 20 p  m](https://github.com/user-attachments/assets/1db3a010-17c1-41c5-a0c9-0a78e177f169)

**Comment by srdavo** [comment]
Solucionado, botón elimiando
